### PR TITLE
upgrade to MinVer 1.0.0-rc.1

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
I guess this is failing for the same reasons as https://github.com/LykkeCorp/apollo/pull/111 ?

**Comment by JoeStead** [comment]
Yeah, it's kind of a pain to fix that

**Comment by adamralph** [comment]
Hopefully @jchannon will just merge it again. 🙂 

Here's one thing you might want to consider: allow all PR's to access the secret env vars, but don't build them automatically. Review them first, and if you see nothing malicious, only then trigger the build.

**Comment by JoeStead** [comment]
Yeah, that would be the sensible thing to do, I don't know if the tooling allows for that though. I'm sure @jchannon could check :)

**Comment by jchannon** [comment]
Looks like we can expose secret variables to forks if we tick a box with a
a massive "ARE YOU SURE?"

Alternatively you can turn off building PRs from forks.

**Comment by JoeStead** [comment]
If we disable auto-building, we could expose them

**Comment by jchannon** [comment]
Eh?

**Comment by JoeStead** [comment]
Don't auto build PRs, manually trigger them, and then we don't have this issue

**Comment by jchannon** [comment]
Well we do if you want manually trigger a build from a fork but we can turn
off the auto build and review and merge

**Comment by adamralph** [comment]
If you switch the building of PR's from forks from auto to manual, then you can review the changes first, and only trigger the build if nothing malicious is being done with the secrets. In that way you can expose the secrets to all builds.

**Comment by jchannon** [comment]
Yup just done that, in the process of testing it now

**Comment by jchannon** [comment]
See https://github.com/LykkeCorp/apollo/pull/129

help command works but run doesnt

**Pull request merged**
