### PR TITLE
upgrade to MinVer 1.0.0-beta.4

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
It looks like the build is failing for an unrelated reason.

**Comment by JoeStead** [comment]
No idea why the build is failing, good start

**Comment by JoeStead** [comment]
Doubly confused, #112 built, this didn't.

**Comment by JoeStead** [comment]
And after thinking about this all morning, it's because we have secret environment variables to run the tests, that aren't accessible via forks (security). Can use admin override for now, but we do need to think of a way around that

**Pull request merged**
