### PR TITLE
Hi Jon

### PR DESCRIPTION
**Pull request by edblackburn**
When creating a PR for Apollo there may be some steps that you've missed, please check them to ensure everything is up to date!

[ ] Does the PR title have a JIRA issue number?

[ ] Has the README been updated if needed?

[ ] Has the Wiki been updated if needed?

[ ] Has Azure Vault been updated if a config option has been altered for Apollo?

### CODE REVIEW

**Comment by JoeStead** [comment]
lol. I don't know why I'm special

**Comment by jchannon** [comment]
because you're from norfolk

**Comment by JoeStead** [comment]
<Ivan Drago joke here>

**Pull request closed without merging**
